spring.application.name=SpringMVCproject

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/SpringEcomm
spring.datasource.username=postgres
spring.datasource.password=1234